# Resume
save-position-on-quit=yes

# Hardware decoding
hwdec=auto

# Modern Wayland/Vulkan rendering
vo=gpu-next
gpu-api=vulkan

# Let Hyprland handle SDR/HDR switching
target-colorspace-hint=auto
target-colorspace-hint-mode=source

# Display synchronization
video-sync=display-resample
interpolation=no

# Scaling
scale=spline36
cscale=spline36

# Subtitles
sub-auto=fuzzy
sub-file-paths=subs:subtitles

# UI
keep-open=yes
osd-bar=yes
