-- ============================================================
-- Color loader
-- Tries to load colors_wallust.lua (generated by wallust run).
-- Falls back to a hardcoded palette so the config never fails
-- on first boot before wallust has run.
--
-- To regenerate after changing wallpaper:
--   scripts/wallust_swww.sh   (or: wallust run /path/to/wallpaper)
--   hyprctl reload
-- ============================================================

local ok, c = pcall(require, "colors_wallust")

if not ok or type(c) ~= "table" then
    -- Fallback: current palette from wallust
    c = {
        background = 0xff030511,
        foreground = 0xffadbedd,
        color0     = 0xff030511,
        color1     = 0xffF58D6F,
        color2     = 0xff355099,
        color3     = 0xff56649D,
        color4     = 0xff4842B8,
        color5     = 0xff9C63E1,
        color6     = 0xffC25BD0,
        color7     = 0xffadbedd,
        color8     = 0xff79859a,
        color9     = 0xffF58D6F,
        color10    = 0xff355099,
        color11    = 0xff56649D,
        color12    = 0xff4842B8,
        color13    = 0xff9C63E1,
        color14    = 0xffC25BD0,
        color15    = 0xffadbedd,
    }
end

return c
