# syntax=docker/dockerfile:1
FROM archlinux:latest

RUN pacman -Syu --noconfirm bash coreutils grep findutils rsync

COPY . /workspace/
RUN chmod -R a+rX /workspace

WORKDIR /workspace
ENTRYPOINT ["bash", "docker/test-tags-arch.sh"]
