splash = false

wallpaper {
    monitor = DP-3
    path = ~/.local/share/wallpapers/jinx.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.local/share/wallpapers/jinx.jpg
    fit_mode = cover
}
