general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.local/share/wallpapers/jinx.jpg
}

label {
    monitor =
    text = $TIME

    color = rgba(d8dee9ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position = -760, 130

    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date "+%A, %d. %B"

    color = rgba(7dd3fccc)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = -760, 65

    halign = center
    valign = center
}

input-field {
    monitor =

    size = 340, 56
    position = -760, -50

    dots_center = true

    fade_on_empty = true
    fade_timeout = 150

    placeholder_text =

    inner_color = rgba(0c0c10cc)
    outer_color = rgba(7dd3fccc)
    font_color = rgba(d8dee9ff)

    outline_thickness = 2
    rounding = 10

    halign = center
    valign = center

    # Authentication feedback
    fail_color = rgba(bf616aff)
    fail_text = <i>Authentication failed</i>
    fail_transition = 250

    capslock_color = rgba(ebcb8bff)
    numlock_color = rgba(ebcb8bff)
}
