#include ~/.config/kitty/kitty-colors.conf

font_family     Fira Code
font_size 	    16.0
bold_font       auto
italic_font      auto
bold_italic_font auto

macos_hide_titlebar no
hide_window_decorations no

background_opacity 0.7
background_blur 44

confirm_os_window_close 0

enable_audio_bell no

selection_foreground #000000
selection_background #F5FBFF

map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# Explicit mappings for C-1 - C-4 so they send CSI u sequences through tmux
map ctrl+1 send_text all \x1b[49;5u
map ctrl+2 send_text all \x1b[50;5u
map ctrl+3 send_text all \x1b[51;5u
map ctrl+4 send_text all \x1b[52;5u
